;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		delete-word
		duplicate-current-line-or-region
		electric-newline-and-maybe-indent
		indent-for-tab-command
		indent-new-comment-line
		js2-line-break
		kill-region
		next5
		prev5
		select-current-line
		sgml-close-tag
		sgml-skip-tag-forward
		sgml-slash
		upcase-region
		))

(setq mc/cmds-to-run-once
      '(
		emmet-expand-line
		ido-find-file
		ido-switch-buffer
		iedit-mode
		js2-mode-show-node
		))
