;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		backward-sexp
		c-electric-delete-forward
		c-electric-slash
		comment-indent-new-line
		delete-word
		downcase-region
		duplicate-current-line-or-region
		emmet-expand-line
		eval-and-replace
		forward-sexp
		indent-for-tab-command
		indent-new-comment-line
		indent-rigidly-right
		kill-region
		next5
		prev5
		select-current-line
		sgml-close-tag
		sgml-delete-tag
		sgml-skip-tag-forward
		sgml-slash
		upcase-region
		web-mode-comment-indent-new-line
		))

(setq mc/cmds-to-run-once
      '(
		helm-projectile
		ido-find-file
		ido-switch-buffer
		iedit-mode
		js2-mode-show-node
		undo-tree-visualize
		))
